name: 'GitHub Actions email Bot'
 
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
    
jobs:
  emailbot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
         

      - name: 'run start.sh'
        run: bash start.sh

      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: email report
          body: file://result.txt
          to: isxychao@outlook.com
          from: GitHub Actions
          content_type: text/plain
       
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: $\{{ secrets.TOKEN_GITHUB }}
          branch: main
